services:
  prometheus-config-init:
    image: busybox
    container_name: prometheus-config-init
    volumes:
      - .:/config
    environment:
      - API_HOST=${API_HOST}
    command: >
      sh -c "sed 's/\$${API_HOST}/'\"$${API_HOST}\"'/g' /config/prometheus.template.yml > /config/prometheus.yml"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "6060:9090"
    depends_on:
      prometheus-config-init:
        condition: service_completed_successfully
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "5050:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped
