apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nginx-demo
  namespace: argocd

spec:
  project: nginx-project

  source:
    repoURL: https://github.com/Mhmdabad/Lab.git
    targetRevision: main
    path: "gitops/argo cd/k8s"

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true